### ISSUE TITLE
Motivation?

### ISSUE THREAD

**Issue by FLamparski** [EdgarsZagorskis/img-background#5]
I'd like to know why this is better than just setting a `background-image` with `background-size: cover` on the body element. Something we've been doing for a long time. If there are benefits to this approach, I'd like to hear them.

**Comment by xnf** [comment]
Hi, sorry that it took a while, didn't notice that this repo had activity. Still it took less than a year :)

Short answer - sure, you can use CSS now. If you only want more or less static image background. 

Long answer - This repo was created in 2014, when IE8 was still a thing, but background-size was added only in IE9.
Around that time term Web Components arrived into spotlight and I was using actual pain at that time (full size images covering whole background) to fiddle around with Polymer library.
Of course, now you can use only CSS, but this (or similar) libraries give you encapsulation power to change backgrounds - add effects, use slideshows without changing the main HTML where the web component is installed or CSS file where the background is used.
